### ISSUE TITLE
Илья, это Антон

### ISSUE THREAD

**Issue by Lilsant** [keldkemp/ConstructorTelegramBots#4]
Ты последний раз заходил в ВК первого января, так шо я не знал, как с тобой связаться, поэтому решил найти тебя здесь
Если прочитаешь, дай ссылку на телегу или новый ВК

**Comment by keldkemp** [comment]
@Lilsant, Привет. Меня везде по нику можно найти) Tg: @keldkemp (https://t.me/KeldKemp)

**Comment by keldkemp** [comment]
@Lilsant, Антон, ты куда подевался то? Дай свой контакт на телеграм тоже
